# Pre-commit hooks configuration for leptos-ws-pro
# Install with: pip install pre-commit && pre-commit install

repos:
  # Custom Rust hooks using local commands
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Format Rust code with rustfmt
        entry: bash -c 'cargo fmt --all -- --check'
        language: system
        files: \.rs$
        pass_filenames: false
      - id: clippy
        name: clippy
        description: Lint Rust code with clippy
        entry: bash -c 'cargo clippy --quiet -- -D warnings'
        language: system
        files: ^src/.*\.rs$
        pass_filenames: false
        stages: [manual]

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        description: Remove trailing whitespace
      - id: end-of-file-fixer
        name: Fix End of Files
        description: Ensure files end with a newline
      - id: check-yaml
        name: Check YAML
        description: Check YAML syntax
      - id: check-json
        name: Check JSON
        description: Check JSON syntax
      - id: check-toml
        name: Check TOML
        description: Check TOML syntax
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for merge conflict markers
      - id: check-added-large-files
        name: Check for large files
        description: Prevent large files from being committed
        args: ['--maxkb=1000']
      - id: check-case-conflict
        name: Check for case conflicts
        description: Check for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict
        name: Check for merge conflicts
        description: Check for merge conflict markers

  # TypeScript/JavaScript formatting (for Playwright tests)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Prettier
        description: Format JavaScript, TypeScript, JSON, and Markdown files
        files: \.(ts|js|json|md)$
        exclude: ^(tests/test-results/|node_modules/)

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        description: Detect potential secrets in code
        exclude: ^(tests/test-results/|node_modules/)
